source 'https://rubygems.org'

gem 'nanoc'
gem 'adsf'
gem 'kramdown'
gem 'sass', '~> 3.4.0'
gem 'compass', '~> 1.0'
gem 'foundation'
gem 'guard'
gem 'guard-nanoc'
gem 'builder'
gem 'nokogiri'
gem 'w3c_validators'
